//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calisanlar
    {
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Soyad { get; set; }
        public Nullable<int> Bölüm { get; set; }
        public string Telefon { get; set; }
        public string Mail { get; set; }
        public string KullaniciAdı { get; set; }
        public string Sifre { get; set; }
        public Nullable<int> RoleId { get; set; }
    
        public virtual Bolumler Bolumler { get; set; }
        public virtual Roller Roller { get; set; }
    }
}
