//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Urunler
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Urunler()
        {
            this.UrunHareketler = new HashSet<UrunHareketler>();
        }
    
        public int Id { get; set; }
        public string Ad { get; set; }
        public string Marka { get; set; }
        public Nullable<decimal> Alis { get; set; }
        public Nullable<decimal> Satis { get; set; }
        public Nullable<short> Stok { get; set; }
        public Nullable<byte> KategoriId { get; set; }
        public Nullable<bool> Durum { get; set; }
    
        public virtual Kategoriler Kategoriler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UrunHareketler> UrunHareketler { get; set; }
    }
}
