//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TeknikServis
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrunKabuller
    {
        public int IslemId { get; set; }
        public Nullable<int> Musteri { get; set; }
        public Nullable<System.DateTime> GelisTarihi { get; set; }
        public Nullable<System.DateTime> CikisTarihi { get; set; }
        public string UrunSeriNo { get; set; }
        public Nullable<bool> UrunDurum { get; set; }
        public string UrunDurumDetay { get; set; }
    
        public virtual Cariler Cariler { get; set; }
    }
}
